[tool.poetry]
name = "alpaca-testing"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
alpaca-py = "^0.40.1"
python-dotenv = "^1.1.0"
black = "^23.12.1"
flask = "^2.3.3"
werkzeug = "^2.3.7"
functions-framework = "^3.8.3"
google-cloud-logging = "^3.12.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"